version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - nodeapp_network

  nodeapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./logs:/var/www/logs
    networks:
      - nodeapp_network

networks:
  nodeapp_network:
    driver: bridge
